name: Stage the app

on: 
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: Yuichi-Ikeda-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: Yuichi-Ikeda-ttt-app
  #################################################
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    
        if: contains(github.event.pull_request.labels.*.name, 'stage')
if:     if: contains(github.event.pull_request.labels.*.name, 'stage')contains(github.event.pull_request.labels.*.name, 'stage')
